CREATE TABLE search_logs (
  id SERIAL PRIMARY KEY,
  source VARCHAR NOT NULL,
  source_id VARCHAR NOT NULL,
  type VARCHAR NOT NULL,
  title VARCHAR NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
